export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "Xcaliber",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Johny",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Alexis",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "Xcaliber",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Leader",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "Supreme",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "John",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "Aman",
  },
  {
    id: 9,
    profilePicture: "person/9.jpeg",
    username: "Inferno",
  },
  {
    id: 10,
    profilePicture: "person/10.jpeg",
    username: "Alex",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love for All Hatred for None.",
    photo: "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    // desc: "Love for All Hatred for None.",
    photo: "post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Love for All Hatred for None.",
    photo: "post/3.jpeg",
    date: "35 mins ago",
    userId: 3,
    like: 11,
    comment: 9,
  },
  {
    id: 4,
    desc: "Love for All Hatred for None.",
    photo: "post/4.jpeg",
    date: "54 mins ago",
    userId: 4,
    like: 4,
    comment: 7,
  },
  {
    id: 5,
    desc: "Love for All Hatred for None.",
    photo: "post/5.jpeg",
    date: "5 mins ago",
    userId: 5,
    like: 32,
    comment: 5,
  },
  {
    id: 6,
    desc: "Love for All Hatred for None.",
    photo: "post/6.jpeg",
    date: "6 mins ago",
    userId: 6,
    like: 36,
    comment: 6,
  },
  {
    id: 7,
    desc: "Love for All Hatred for None.",
    photo: "post/7.jpeg",
    date: "7 mins ago",
    userId: 1,
    like: 37,
    comment: 7,
  },
  {
    id: 8,
    desc: "Love for All Hatred for None.",
    photo: "post/8.jpeg",
    date: "8 mins ago",
    userId: 8,
    like: 38,
    comment: 8,
  },
  {
    id: 9,
    desc: "Love for All Hatred for None.",
    photo: "post/9.jpeg",
    date: "9 mins ago",
    userId: 9,
    like: 92,
    comment: 9,
  },
  {
    id: 10,
    desc: "Love for All Hatred for None.",
    photo: "post/10.jpeg",
    date: "4 mins ago",
    userId: 10,
    like: 2,
    comment: 11,
  },
];
